% clear all
% close all
% clc

fs = 100;
ifs = 100;
beats = 80;
noiseAmplitude = 0.05;
beatRate = 64;
beatDeviation = 2;
lfhfratio = 0.5;

[ECGSignal, ~] = ecgsyn(fs, ...
                        beats, ...
                        noiseAmplitude, ...
                        beatRate,...
                        beatDeviation, ...
                        lfhfratio, ...
                        ifs);


ECGTime = (1:numel(ECGSignal))/fs;
ECGPeaks = ampd(ECGSignal);

fig = figure(1);

set(fig, ...
    'Color', [1 1 1], ...
    'Position', [50 50 900 400])

axs = axes();

xLim = [0, max(ECGTime)];
yLim = [-0.5 1.5];

xTicks = linspace(0, max(ECGTime),10);
yTicks = -0.5:0.25:1.75;

xTicksLabel = sprintf('%.2f|', xTicks);
yTicksLabel = sprintf('%.2f|', yTicks);

set(axs, ...
    'NextPlot', 'Add', ...
    'Box', 'On')

set(axs, ...
    'XLim', xLim, ...
    'XTick', xTicks, ...
    'XGrid', 'On', ...
    'XTickLabel', xTicksLabel, ...
    'YLim', yLim, ...
    'YTick', yTicks, ...
    'YGrid', 'On', ...
    'YTickLabel', yTicksLabel)

set(get(axs,'XLabel'), ...
    'String', 'Time [s]',...
    'FontSize', 12)

set(get(axs,'YLabel'), ...
    'String', 'Amplitude [mV]',...
    'FontSize', 12)

set(get(axs,'Title'), ...
    'String', 'Simulated electrocardiogram signal',...
    'FontSize', 16)

plot(ECGTime,ECGSignal,'b-',ECGTime(ECGPeaks),ECGSignal(ECGPeaks),'r*');